// Run with node_modules/.bin/electron scripts/verify-ui.cjs.
const { app, BrowserWindow, dialog } = require('electron');
const fs = require('fs');
const os = require('os');
const path = require('path');
const assert = require('node:assert/strict');
const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'almost-editor-ui-'));
app.setPath('userData', temporary);
fs.writeFileSync(path.join(temporary, 'config.json'), JSON.stringify({ theme: 'system', fontSize: 15 }));
const project = path.join(temporary, 'blog');
fs.mkdirSync(path.join(project, 'content/posts/first'), { recursive: true });
fs.mkdirSync(path.join(project, 'content/posts/second'), { recursive: true });
fs.writeFileSync(path.join(project, 'content/posts/first/index.md'), '+++\ntitle = "A morning in Berlin"\n+++\n\n' + Array.from({ length: 80 }, (_, i) => `## Section ${i}\n\nA paragraph about photography and walking through the city.\n`).join('\n'));
fs.writeFileSync(path.join(project, 'content/posts/second/index.md'), '---\ntitle: Film photography\n---\n\nHello');
dialog.showOpenDialogSync = () => [project];
require('../main');
const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
setTimeout(() => { console.error('UI checks timed out'); app.exit(1); }, 30000).unref();
app.whenReady().then(async () => {
  try {
    const window = BrowserWindow.getAllWindows()[0];
    const errors = [];
    window.webContents.on('console-message', (_event, _level, message) => { if (/ReferenceError|TypeError|SyntaxError/.test(message)) errors.push(message); });
    if (window.webContents.isLoading()) await new Promise(resolve => window.webContents.once('did-finish-load', resolve));
    const js = source => window.webContents.executeJavaScript(source);
    const capture = async destination => {
      window.show(); window.focus();
      await js(`new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))`);
      await pause(200);
      fs.writeFileSync(destination, (await window.webContents.capturePage()).toPNG());
    };
    await pause(200);
    assert.equal(await js(`document.getElementById('welcome').classList.contains('hidden')`), false);
    assert.equal((await js(`window.api.getConfig()`)).syncScroll, false);
    assert.equal(await js(`document.getElementById('view-controls').getClientRects().length`), 0);
    await js(`document.getElementById('settings-button').click()`);
    assert(await js(`document.getElementById('settings-popover').matches(':popover-open')`));
    window.webContents.sendInputEvent({ type: 'keyDown', keyCode: 'Escape' });
    window.webContents.sendInputEvent({ type: 'keyUp', keyCode: 'Escape' });
    await pause(50);
    assert.equal(await js(`document.getElementById('settings-popover').matches(':popover-open')`), false);
    await js(`document.getElementById('settings-button').click(); document.getElementById('image-options').click()`);
    assert.equal(await js(`document.getElementById('image-options-dialog').classList.contains('hidden')`), false);
    await js(`document.getElementById('cancel-image-options').click()`);
    await pause(50);
    assert.equal(await js(`document.activeElement.id`), 'settings-button');
    await js(`document.getElementById('welcome-project').click()`);
    await pause(100);
    assert.deepEqual(await js(`[...document.querySelectorAll('.post-title')].map(el => el.textContent)`), ['A morning in Berlin', 'Film photography']);
    await js(`document.getElementById('post-search').value = 'photography'; document.getElementById('post-search').dispatchEvent(new Event('input'))`);
    assert.equal(await js(`document.querySelectorAll('.post-entry:not([hidden])').length`), 1);
    await js(`document.getElementById('post-search').value = ''; document.getElementById('post-search').dispatchEvent(new Event('input')); document.querySelector('.post-entry').click()`);
    await pause(100);
    assert.equal(await js(`document.querySelector('.post-entry.active').getAttribute('aria-current')`), 'page');
    const width = await js(`document.getElementById('post-sidebar').getBoundingClientRect().width`);
    await js(`document.getElementById('sidebar-resizer').dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowRight', bubbles: true }))`);
    assert.equal(await js(`document.getElementById('post-sidebar').getBoundingClientRect().width`), width + 10);
    // Resizing stores an inline width; hiding preview must temporarily override it.
    await js(`document.getElementById('preview-resizer').dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowLeft', shiftKey: true, bubbles: true }))`);
    const paneSizes = () => js(`['editor-pane', 'preview'].map(id => document.getElementById(id).getBoundingClientRect().width)`);
    const originalBounds = window.getBounds();
    const originalPanes = await paneSizes();
    window.setSize(originalBounds.width - 180, originalBounds.height);
    await pause(150);
    const smallerPanes = await paneSizes();
    assert(smallerPanes[0] < originalPanes[0], 'Editor should shrink with the window');
    assert(smallerPanes[1] < originalPanes[1], 'Preview should shrink with the window');
    assert(Math.abs(smallerPanes[0] / smallerPanes[1] - originalPanes[0] / originalPanes[1]) < .01, 'Chosen split ratio should be preserved');
    window.setBounds(originalBounds);
    await pause(150);
    const restoredPanes = await paneSizes();
    assert(Math.abs(restoredPanes[0] - originalPanes[0]) < 1);
    assert(Math.abs(restoredPanes[1] - originalPanes[1]) < 1);
    const splitWidth = await js(`document.getElementById('editor-pane').getBoundingClientRect().width`);
    await js(`document.getElementById('toggle-preview').click()`);
    await pause(50);
    assert(await js(`Math.abs(document.getElementById('editor-pane').getBoundingClientRect().width - document.getElementById('panes').getBoundingClientRect().width) < 1`));
    assert.equal(await js(`document.getElementById('preview-resizer').getClientRects().length`), 0);
    await js(`document.querySelectorAll('.post-entry')[1].click()`);
    await pause(50);
    assert(await js(`Math.abs(document.getElementById('editor-pane').getBoundingClientRect().width - document.getElementById('panes').getBoundingClientRect().width) < 1`));
    await js(`document.getElementById('toggle-preview').click()`);
    await pause(50);
    assert.equal(await js(`document.getElementById('editor-pane').getBoundingClientRect().width`), splitWidth);
    await js(`document.querySelector('.post-entry').click()`);
    await pause(50);
    await js(`document.getElementById('sync-scroll').click()`);
    await pause(100);
    await js(`const scroller = document.querySelector('.cm-scroller'); scroller.scrollTop = (scroller.scrollHeight - scroller.clientHeight) / 2`);
    await pause(250);
    const fraction = await js(`(() => { const p = document.getElementById('preview'); return p.scrollTop / (p.scrollHeight - p.clientHeight); })()`);
    assert(Math.abs(fraction - .5) < .08, `Preview fraction: ${fraction}`);
    await js(`document.getElementById('preview').scrollTop = 0`);
    await pause(250);
    const editorAtPreviewStart = await js(`document.querySelector('.cm-scroller').scrollTop`);
    assert(editorAtPreviewStart > 80, `Preview start should align after front matter: ${editorAtPreviewStart}`);
    await js(`document.querySelector('.cm-scroller').scrollTop = 0`);
    await pause(250);
    assert.equal(await js(`document.getElementById('preview').scrollTop`), 0);
    assert.equal((await js(`window.api.getConfig()`)).syncScroll, true);
    await js(`document.getElementById('new-post').click(); const title = document.getElementById('new-post-heading'); title.value = 'Café in Berlin'; title.dispatchEvent(new Event('input'))`);
    assert.equal(await js(`document.getElementById('new-post-name').value`), 'cafe-in-berlin');
    await js(`document.querySelector('#new-post-form button[type=submit]').focus()`);
    window.webContents.sendInputEvent({ type: 'keyDown', keyCode: 'Tab' });
    window.webContents.sendInputEvent({ type: 'keyUp', keyCode: 'Tab' });
    await pause(50);
    assert.equal(await js(`document.activeElement.id`), 'new-post-heading');
    await capture('/tmp/almost-editor-ui-new-post.png');
    await js(`document.getElementById('new-post-form').requestSubmit()`);
    await pause(100);
    assert(fs.readFileSync(path.join(project, 'content/posts/cafe-in-berlin/index.md'), 'utf8').includes('title = "Café in Berlin"'));
    assert(fs.statSync(path.join(project, 'content/posts/cafe-in-berlin/images')).isDirectory());
    await js(`document.getElementById('editor-pane').style.flex = '0 0 240px'`);
    await pause(100);
    await js(`document.getElementById('more-format').click()`);
    assert(await js(`document.getElementById('format-popover').matches(':popover-open')`));
    await js(`document.querySelector('#format-popover [data-format="rule"]').click()`);
    assert.equal(await js(`document.getElementById('format-popover').matches(':popover-open')`), false);
    assert((await js(`document.querySelector('.cm-content').textContent`)).includes('---'));
    await js(`document.getElementById('show-welcome').click()`);
    await pause(100);
    assert(await js(`document.querySelectorAll('#recent-documents button').length >= 2`));
    await capture('/tmp/almost-editor-ui-home.png');
    await js(`document.querySelectorAll('#recent-documents button')[1].click()`);
    await pause(100);
    assert.equal(await js(`document.title`), 'Almost Editor – A morning in Berlin');
    assert.equal(window.getTitle(), 'Almost Editor – A morning in Berlin');
    await js(`document.getElementById('theme-select').value = 'light'; document.getElementById('theme-select').dispatchEvent(new Event('change'))`);
    await pause(100);
    await capture('/tmp/almost-editor-ui-light.png');
    await js(`document.getElementById('theme-select').value = 'dark'; document.getElementById('theme-select').dispatchEvent(new Event('change'))`);
    await pause(100);
    await capture('/tmp/almost-editor-ui-dark.png');
    await js(`document.getElementById('editor-pane').style.flex = '0 0 240px'`);
    await pause(50);
    assert(await js(`(() => { const bar = document.getElementById('format-toolbar'); return bar.scrollWidth <= bar.clientWidth; })()`));
    await capture('/tmp/almost-editor-ui-narrow.png');
    assert(await js(`document.querySelectorAll('#format-popover [data-format]').length > 0`));
    await js(`document.getElementById('toggle-preview').click()`);
    await pause(100);
    assert.equal(await js(`document.querySelectorAll('#format-popover [data-format]').length`), 0);
    assert.equal(await js(`document.getElementById('more-format').hidden`), true);
    assert.equal(await js(`document.querySelectorAll('#format-toolbar [data-format]').length`), 10);
    await js(`document.getElementById('toggle-preview').click()`);
    await pause(100);
    assert(await js(`document.querySelectorAll('#format-popover [data-format]').length > 0`));
    assert.equal(await js(`document.getElementById('sync-scroll').getAttribute('aria-pressed')`), 'true');
    await js(`window.api.saveConfig({ recentDocuments: [{ filePath: '/tmp/forged.md' }] })`);
    assert.equal((await js(`window.api.openRecent('/tmp/forged.md')`)).ok, false);
    await js(`document.getElementById('show-welcome').click()`);
    await pause(50);
    await js(`document.getElementById('clear-recents').click()`);
    await pause(50);
    assert.deepEqual((await js(`window.api.getConfig()`)).recentDocuments, []);
    assert(fs.existsSync(path.join(project, 'content/posts/first/index.md')));
    assert.deepEqual(errors, []);
    console.log('UI checks passed: welcome, TOML/YAML titles, search, keyboard resize, scroll sync, title-first creation, recent reopening, both themes.');
    app.exit(0);
  } catch (error) { console.error(error); app.exit(1); }
  finally { fs.rmSync(temporary, { recursive: true, force: true }); }
});
